apiVersion: 1
deleteDatasources:
  - name: prometheus
    orgId: 1
datasources:
  - name: prometheus
    type: prometheus
    orgId: 1
    isDefault: true
    basicAuth: false
    editable: true
    access: proxy
    url: http://prometheus:9090
    timeout: 60
    httpMethod: GET
