version: 1
disable_existing_loggers: False
formatters:
  default:
    datefmt: "%Y-%m-%dT%H:%M:%S"
    format: '[%(asctime)s.%(msecs)03dZ] %(levelname)s %(message)s'
handlers:
  console:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stdout
loggers:
  root:
    level: DEBUG
    handlers:
      - console
    propagate: no
