global:
  resolve_timeout: 5m

templates:
  - '/etc/alertmanager-templates/*.tmpl'

route:
  group_by: ['alertname', 'service']
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 5h
  receiver: "default-email"

receivers:
  - name: 'default-email'
    email_configs:
      - to: 'example@domain.com'
        require_tls: false
