envs:
  local:
    apps:
      bootstrap_parent:
        params:
          parent_app: null
      bootstrap:
        params:
          parent_app: bootstrap_parent
      common:
        vars:
          argocd:
            sync_wave: -1
      prometheus: {}
      kube_state_metrics: {}
      node_exporter: {}
      grafana: {}
    params:
      parent_app: bootstrap
vars:
  __application:
    path: examples/monitoring_stack/output/${env_name}/${app_name}
  argocd:
    source:
      repo_url: https://github.com/Karandash8/make-argocd-fly.git
      target_revision: 181-add-examples-of-real-world-applications
    sync_policy:
      automated:
        selfHeal: true
  monitoring:
    namespace: monitoring
    prometheus_n_replicas: 2
    prometheus_version: 3.4.1
    alertmanager_n_replicas: 2
    kube_state_metrics_version: 2.15.0
    node_exporter_version: 4.47.3
    grafana_version: 12.0.2
