envs:
  local:
    apps:
      bootstrap_parent:
        params:
          parent_app: null
      bootstrap:
        params:
          parent_app: bootstrap_parent
      common:
        vars:
          argocd:
            sync_wave: -1
      prometheus: {}
      kube_state_metrics: {}
    params:
      parent_app: bootstrap
vars:
  __application:
    path: examples/monitoring_stack/output/${env_name}/${app_name}
  argocd:
    source:
      repo_url: https://github.com/Karandash8/make-argocd-fly.git
      target_revision: 181-add-examples-of-real-world-applications
    sync_policy:
      automated:
        selfHeal: true
  monitoring:
    namespace: monitoring
    prometheus__n_replicas: 2
    prometheus__version: 3.4.1
    alertmanager__n_replicas: 2
    kube_state_metrics__version: 2.15.0
