envs:
  local:
    apps:
      bootstrap_parent:
        params:
          parent_app: null
      bootstrap:
        params:
          parent_app: bootstrap_parent
      common:
        vars:
          argocd:
            sync_wave: -1
      prometheus: {}
      kube_state_metrics: {}
      node_exporter: {}
      grafana: {}
      alertmanager: {}
    params:
      parent_app: bootstrap
vars:
  argocd:
    finalizers: []
    source:
      repo_url: YOUR_GIT_REPO_URL
    sync_policy:
      automated:
        selfHeal: true
      syncOptions:
        - ServerSideApply=true
        - CreateNamespace=true
  monitoring:
    namespace: monitoring
    prometheus_n_replicas: 2
    prometheus_version: 3.4.1
    alertmanager_n_replicas: 2
    alertmanager_version: 0.28.1
    kube_state_metrics_version: 2.15.0
    node_exporter_version: 4.47.3
    grafana_version: 12.0.2
