# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Coverage

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  pytest:
    name: "Run pytest with Python ${{ matrix.python-version }}"
    runs-on: make-argocd-fly

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.11"
          # - "3.12" # there is no 3.12 for noble yet (https://github.com/deadsnakes/python3.12)

    steps:
      - uses: actions/checkout@v4
      - if: ${{ runner.arch == 'arm64' }}
        name: Set up Python
        uses: deadsnakes/action@v3.1.0
        with:
          python-version: "${{ matrix.python-version }}"
      - if: ${{ runner.arch == 'amd64' }}
        name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python-version }}"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements.dev.txt ]; then pip install -r requirements.dev.txt; fi
      - name: "Run tox for ${{ matrix.python-version }}"
        run: |
          python -m tox
      - name: "Upload coverage data"
        uses: actions/upload-artifact@v4
        with:
          name: covdata
          path: .coverage.*
          include-hidden-files: true

  coverage:
    name: Run coverage
    needs: pytest
    runs-on: make-argocd-fly
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"

      - if: ${{ runner.arch == 'arm64' }}
        name: Set up Python
        uses: deadsnakes/action@v3.1.0
        with:
          python-version: "3.11"
      - if: ${{ runner.arch == 'amd64' }}
        name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements.dev.txt ]; then pip install -r requirements.dev.txt; fi

      - name: "Download coverage data"
        uses: actions/download-artifact@v4
        with:
          name: covdata

      - name: "Combine"
        run: |
          python -m tox -e coverage
          export TOTAL=$(python -c "import json;print(json.load(open('coverage.json'))['totals']['percent_covered_display'])")
          echo "total=$TOTAL" >> $GITHUB_ENV
          echo "### Total coverage: ${TOTAL}%" >> $GITHUB_STEP_SUMMARY

      - name: "Make badge"
        uses: schneegans/dynamic-badges-action@v1.7.0
        continue-on-error: false
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: 26eb92c97bbfac22b938afebac85e7cd
          filename: covbadge.json
          label: Coverage
          message: ${{ env.total }}%
          minColorRange: 50
          maxColorRange: 90
          valColorRange: ${{ env.total }}
